[build]
    functions = "functions"
[[redirects]]
    from = "/*"
    to = "/.netlify/functions/:splat"
    status = 200
    force = true

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*" 